name: Build & Publish Release APK from Master Branch

# 标签方式自动部署
on:
  push:
    tags:
      - v[1-9]+.[0-9]+.[0-9]+
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      # 拉取test分支代码
      - uses: actions/checkout@v1
        with:
          ref: master

      # 克隆私有的密钥库, 用于打包时签名，该仓库为私有库
      - name: clone project keystore
        uses: actions/checkout@v2
        with:
          repository: aaronlinv/AndroidKeystore
          path: AndroidKeystore
          token: ${{secrets.JuiceTimetable}}

      # 移动 AndroidKeystore 到项目父文件夹
      - name: move keystore dir to parent
        id: move_keystore_dir
        run: mv AndroidKeystore ..

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Make Gradle executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build

      - name: Build apk package
        run: ./gradlew clean assembleRelease --stacktrace

        # 发行包
      - name: Upload apk to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.JuiceTimetable }}
          file: ./app/build/outputs/apk/release/app-release.apk
          asset_name: JuiceTimeTable-${{ steps.get_version.outputs.VERSION }}.apk
          tag: ${{ github.ref }}
          overwrite: true